version: "3"
services:
  qinglong:
    restart: always
    container_name: qinglong
    # alpine 基础镜像版本
    image: whyour/qinglong:latest
    # debian-slim 基础镜像版本
    # image: whyour/qinglong:debian  
    volumes:
      - /opt/docker/qinglong:/ql/data
    ports:
      - "5700:5700"
    environment:
      # 部署路径非必须，以斜杠开头和结尾，比如 /test/
      QlBaseUrl: '/'
